# Generated by Django 5.2.6 on 2025-09-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('MovieID', models.IntegerField(primary_key=True, serialize=False)),
                ('MovieTitle', models.CharField(max_length=255)),
                ('Actor1Name', models.CharField(max_length=100)),
                ('Actor2Name', models.CharField(blank=True, max_length=100, null=True)),
                ('DirectorName', models.CharField(max_length=100)),
                ('MovieGenre', models.CharField(max_length=50)),
                ('ReleaseYear', models.IntegerField()),
            ],
        ),
    ]
